spring.application.name=product

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:problem_bank}
spring.datasource.username=${POSTGRES_USER:problem_bank}
spring.datasource.password=${POSTGRES_PASSWORD:problem_bank_local}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
